services:
  db:
    image: postgres:17
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  schemaspy:
    build: .
    platform: linux/amd64
    volumes:
      - ./schemaspy/config/schemaspy.properties:/config/schemaspy.properties:ro
      - ./docs:/output
    command: java -jar schemaspy.jar -configFile /config/schemaspy.properties -u ${POSTGRES_USER} -p ${POSTGRES_PASSWORD}